[package]
name = "hello-world-wasm-rust"
version = "0.1.0"
authors = ["Дамјан Георгиевски <gdamjan@gmail.com>"]
edition = "2018"

[lib]
crate-type =["cdylib"]

[profile.release]
lto = true

[dependencies]
